name: osml_models
channels:
  - conda-forge
dependencies:
  - conda-forge::gdal=3.7.0
  - conda-forge::proj=9.2.1
  - conda-forge::cython=0.29.36
  - conda-forge::libjpeg-turbo=2.1.5.1
  - conda-forge::pytorch=2.0.0
  - conda-forge::torchvision=0.15.2
  - conda-forge::pycocotools=2.0.6
  - conda-forge::detectron2=0.6
  - # These two are left unpinned to work on MAC+Linux OS
  - conda-forge::libgcc
  - conda-forge::cudatoolkit-dev
