name: osml_models

dependencies:
  - python
  - gdal
  - libgcc
  - proj
  - cython
  - cudatoolkit-dev
  - libjpeg-turbo
  - pytorch
  - torchvision
  - pycocotools
  - detectron2

channels:
  - conda-forge
  - pytorch