name: osml_models

dependencies:
  - nvidia/label/cuda-11.7.0::cuda
  - conda-forge::python=3.11
  - conda-forge::gdal=3.7.0
  - conda-forge::proj=9.2.1
channels:
  - conda-forge
  - nvidia/label/cuda-11.7.0
