# Copyright 2023-2024 Amazon.com, Inc. or its affiliates.

name: osml_models
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10.12
  - conda-forge::gdal=3.7.2
  - conda-forge::proj=9.3.0
  - pip:
      - json-logging==1.3.0
      - boto3==1.34.104
      - setuptools==68.0.0
      - argparse==1.4.0
      - flask==2.3.3
      - waitress==2.1.2
      - shapely==2.0.1
      - matplotlib==3.7.2
