name: docker publish

on:
  workflow_call:

env:
  REGISTRY: awsosml
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
