name: docker build

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 30000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Build the Docker Container
      run: docker build . --file docker/Dockerfile --tag osml-models:$(date +%s)
