name: Build Docker Container

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Free up the build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 30000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag osml-models:$(date +%s)
