name: Publish OSML Models DockerHub Container

on:
  workflow_call:

env:
  REGISTRY: awsosml
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Free up the build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 40000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Publish Container to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
