name: docs

on:
  workflow_dispatch:
  workflow_call:

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Miniconda with osml_model_sam3 env
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          activate-environment: osml_model_sam3
          environment-file: conda/environment-sam3.yml
          channels: conda-forge
          auto-activate-base: false
          miniforge-version: latest
      - name: Build Docs
        run: |
          python -m pip install --upgrade pip tox
          tox -e docs
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .tox/docs/tmp/html/
          force_orphan: true
